### ISSUE TITLE
Use undirected wiring diagrams instead of directed ones

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/AlgebraicRelations.jl#6]
This should be helpful in general, including with issues like https://github.com/AlgebraicJulia/Catlab.jl/issues/164.

**Comment by epatters** [comment]
I plan to implement https://github.com/AlgebraicJulia/Catlab.jl/issues/218 soon, which should help.

**Comment by jpfairbanks** [comment]
@bosonbaas is this done with the latest commits?

**Comment by bosonbaas** [comment]
This issue has now been resolved with the introduction of the ACSet backend in v0.2.0
